#ifndef SHEPHERD_VERSION_H
#define SHEPHERD_VERSION_H

#define SHEPHERD_VERSION "2.2.8"
#define SHEPHERD_VERSION_MAJOR 2
#define SHEPHERD_VERSION_MINOR 2
#define SHEPHERD_VERSION_PATCH 8

#endif // SHEPHERD_VERSION_H
