#ifndef SHEPHERD_VERSION_H
#define SHEPHERD_VERSION_H

#define SHEPHERD_VERSION "2.32.1"
#define SHEPHERD_VERSION_MAJOR 2
#define SHEPHERD_VERSION_MINOR 32
#define SHEPHERD_VERSION_PATCH 1

#endif // SHEPHERD_VERSION_H
