#ifndef SHEPHERD_VERSION_H
#define SHEPHERD_VERSION_H

#define SHEPHERD_VERSION "2.40.0"
#define SHEPHERD_VERSION_MAJOR 2
#define SHEPHERD_VERSION_MINOR 40
#define SHEPHERD_VERSION_PATCH 0

#endif // SHEPHERD_VERSION_H
